### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by barney2229** [jcul/HaliphaxHideRoot#4]
Halifax decided to patch this in the last update :-(

**Comment by steve51184** [comment]
Stay on the old v6.0 Halifax app until this mod is updated via xposed :)

**Comment by barney2229** [comment]
Do you have the apk as I updated 😁

**Comment by steve51184** [comment]
Sure you can get it from the official site:

http://novalauncher.com/apk/NovaLauncher_3.3.apk

**Comment by steve51184** [comment]
Oops got mixed up let me see if I can get Halifax v6 apk and not Nova lol

**Comment by barney2229** [comment]
I think I have it from a Google search thank you though :-)

**Comment by barney2229** [comment]
Scrap that couldn't parse package

**Comment by steve51184** [comment]
Will have another look.. Highest I've found is 5.1 :/

Can I extract the apk from my phone anyhow?

**Comment by barney2229** [comment]
Yeah it will be in root/data/app folder with any root file manager

**Comment by sbesage** [comment]
Eagerly hoping for a fix for this!

**Comment by steve51184** [comment]
Here's the working v6 apk until a fix is out:

https://www.dropbox.com/s/gw91re8cwffxj29/com.grppl.android.shell.halifax-2.apk?dl=0

**Comment by jcul** [comment]
Hey guys, not at home at the moment, but will try have a look at the new apk tomorrow evening and see if I can sort out a fix. Hopefully it's not too drastically changed.

**Comment by sbesage** [comment]
I'm getting error parsing file on that apk Steve,  tried renaming and uninstalling the updated apk also. Will keep my eyes out for any news!

**Comment by sbesage** [comment]
Any news please jcul?

**Comment by jcul** [comment]
I've been a bit busy with work lately, so haven't had a chance to look into it properly.
I did dissassemble the apk though and have a look around.

The cryptomathic Malware / Root detection stuff has changed quite a bit, from what I can tell it shouldn't be too difficult to bypass it same as before, but I won't know for sure until I poke around a bit more.

I don't actually live in the UK and my current phone isn't even rooted, so had to dig out my old phone to play around.
Hopefully I should be able to find some time this weekend.

**Comment by ididmytime** [comment]
Just wanna say thanks jcul for your work with this, if you ever decide to open a donation page up let us know as I'm sure I wouldn't be the only one who would gladly support your efforts.

**Comment by jcul** [comment]
Just updated the module, and hopefully should be working now for the newer version of the app.
Should still work with the older version too. I don't know if Lloyds, TSB or BoS have updated yet, so hopefully shouldn't break for them.

Let me know if you guys have any problems.

@ididmytime Absolutely no need for donations at all, but if you would like to give a few euros, I'm raising some money for a charity run here: http://give2go.ie/profile/50710

**Comment by steve51184** [comment]
Hi in on v7 of the Halifax app and this still isn't working I'm trying to set up online banking and I get past the 'phone call verification' but always get an 'app inacceptable, sorry we are experiencing technical problems please try again later'
